extends: airbnb-base
env:
  browser: true
rules:
  no-unused-expressions: [error, { allowShortCircuit: true }]
  prefer-const: [error, { destructuring: all }]
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
